a = int(input("İnteger Value: "))
b = str(input("String Value: "))
c = float(input("Float Value: "))
d = bool(input("Boolean Value: "))
e = complex(input("Complex Value: "))

print("İnteger Value's Class :{}".format(type(a)))
print("String Value's Class :{}".format(type(b)))
print("Float Value's Class :{}".format(type(c)))
print("Boolean Value's Class :{}".format(type(d)))
print("Complex Value's Class :{}".format(type(e)))